import ps5 from "../assets/ps5.jpg";
import metalgearps1 from "../assets/metalgearps1.webp";
import jeuxdreamcast from "../assets/jeuxdreamcast.jpg";
import manettedreamcast from "../assets/manettedreamcast1.webp";
import dreamcast from "../assets/dreamcast.jpg";
import lotjeuxps4 from "../assets/lotjeuxps4.jpg";
import nintendo64 from "../assets/nintendo64.jpg";
import manetteps5 from "../assets/manetteps5.jpg";
import manetteswitch from "../assets/manetteswitch.jpg";
import gamecube from "../assets/gamecube.jpg";

export const plantList = [
  {
    name: "Lot jeux ps4",
    category: "jeux",
    id: "1ed",
    condition: 3,
	description: "Lot de jeux ps4",
    // light: 1,
    cover: lotjeuxps4,
    price: "20",
    // isBestSale: true,
    // isSpecialOffer: false,
  },
  {
    name: "Manette dreamcast",
    category: "accessoires",
    id: "2ab",
    condition: 2,
	description: "Manette dreamcast",
    // light: 1,
    cover: manettedreamcast,
    price: "25",
    // isBestSale: false,
    // isSpecialOffer: true,
  },
  {
    name: "Manette ps5",
    category: "accessoires",
    id: "3sd",
    price: "19",
    condition: 1,
	description: "Manette ps5",
    // light: 2,
    cover: manetteps5,
    // isBestSale: true,
    // isSpecialOffer: false,
  },
  {
    name: "Metal gear ps1",
    category: "jeux",
    id: "4kk",
    price: "20",
    condition: 3,
	description: "Jeux metal gear solide sur PS1 complet",
    // light: 3,
    cover: metalgearps1,
    // isBestSale: false,
    // isSpecialOffer: true,
  },
  {
    name: "Nintendo 64",
    category: "consoles",
    id: "5pl",
    price: "40",
    condition: 1,
	description: "Console nintendo 64",
    // light: 3,
    cover: nintendo64,
    // isBestSale: true,
    // isSpecialOffer: false,
  },
  {
    name: "Dreamcast",
    category: "consoles",
    id: "6uo",
    price: "120",
    condition: 2,
	description: "Console Dreamcast",
    // light: 3,
    cover: dreamcast,
    // isBestSale: false,
    // isSpecialOffer: true,
  },
  {
    name: "Ps5",
    category: "consoles",
    id: "7ie",
    price: "400",
    condition: 2,
	description: "Console PS5",
    // light: 2,
    cover: ps5,
    // isBestSale: true,
    // isSpecialOffer: false,
  },
  {
    name: "Jeux dreamcast",
    category: "jeux",
    id: "8fp",
    price: "13",
    condition: 3,
	description: "Lot de jeux Dreamcast",
    // light: 1,
    cover: jeuxdreamcast,
    // isBestSale: true,
    // isSpecialOffer: false,
  },
  {
    name: "Manette switch",
    category: "accessoires",
    id: "9vn",
    price: "10",
    condition: 3,
	description: "Manette nintendo switch non officiel",
    // light: 1,
    cover: manetteswitch,
    // isBestSale: false,
    // isSpecialOffer: true,
  },
  {
    name: "Game cube",
    category: "consoles",
    id: "10gc",
    price: "470",
    condition: 3,
	description: "Console nintendo Game cube complète et collector",
    // light: 1,
    cover: gamecube,
    // isBestSale: false,
    // isSpecialOffer: true,
  },
];
